// <auto-generated />
namespace Models.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddStyleNo_Change_ProductID1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStyleNo_Change_ProductID1));
        
        string IMigrationMetadata.Id
        {
            get { return "201306122237045_AddStyleNo_Change_ProductID1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
