// <auto-generated />
namespace Models.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddStyleNo_Change_ProductID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStyleNo_Change_ProductID));
        
        string IMigrationMetadata.Id
        {
            get { return "201306122235170_AddStyleNo_Change_ProductID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
